### ISSUE TITLE
Unable to use h3-presto plugin

### ISSUE THREAD

**Issue by sujoyuta** [foursquare/h3-presto#19]
When I am trying to deploy prestodb using k8s then the coordinator and worker pods come up and I do see that the H3Plugin is getting loaded successfully.

```
2024-03-19T23:38:15.129Z        INFO    main    com.facebook.airlift.bootstrap.LifeCycleManager Life cycle startup complete. System ready.
2024-03-19T23:38:15.129Z        INFO    main    com.facebook.presto.server.PluginManager        -- Loading plugin /var/presto/data/plugin/H3Plugin --
2024-03-19T23:38:15.131Z        WARN    main    com.facebook.presto.server.PluginManager        No service providers of type com.facebook.presto.spi.Plugin
2024-03-19T23:38:15.131Z        INFO    main    com.facebook.presto.server.PluginManager        -- Finished loading plugin /var/presto/data/plugin/H3Plugin --
2024-03-19T23:38:15.131Z        INFO    main    com.facebook.presto.server.PluginManager        -- Loading plugin /var/presto/data/plugin/accumulo --
2024-03-19T23:38:15.318Z        INFO    main    com.facebook.presto.server.PluginManager        Installing com.facebook.presto.accumulo.AccumuloPlugin
2024-03-19T23:38:15.347Z        INFO    main    com.facebook.presto.server.PluginManager        Registering connector accumulo
2024-03-19T23:38:15.348Z        INFO    main    com.facebook.presto.server.PluginManager        -- Finished loading plugin /var/presto/data/plugin/accumulo --
2024-03-19T23:38:15.348Z        INFO    main    com.facebook.presto.server.PluginManager        -- Loading plugin /var/presto/data/plugin/atop --
2024-03-19T23:38:15.421Z        INFO    main    com.facebook.presto.server.PluginManager        Installing com.facebook.presto.atop.AtopPlugin
```

From the prestodb source code (https://github.com/prestodb/presto/blob/7543c0a1cfcbe2e4243403222546bcdc2cb7ff27/presto-main/src/main/java/com/facebook/presto/server/PluginManager.java#L211) It seems like this is the expected behavior.

I followed the build instructions documented in the README of this repo and build the shadow jar and then created a directory called ```H3Plugin``` and put the jar there.( I have also tried to name this dir as ```h3``` with the same result BTW)

After this when I connect to my presto server using presto-cli and run the following queries I see the following

```
presto> SELECT h3_latlng_to_cell(20.0, 10.0, 9) as hex;
Query 20240320_013614_00002_kwne7 failed: line 1:8: Function h3_latlng_to_cell not registered
SELECT h3_latlng_to_cell(20.0, 10.0, 9) as hex

show functions like '%h3%';
 Function | Return Type | Argument Types | Function Type | Deterministic | Description | Variable Arity | Built In | Temporary | Language 
----------+-------------+----------------+---------------+---------------+-------------+----------------+----------+-----------+----------
(0 rows)

Query 20240319_235945_00003_kwne7, FINISHED, 1 node
Splits: 67 total, 67 done (100.00%)
[Latency: client-side: 0:02, server-side: 0:01] [0 rows, 0B] [0 rows/s, 0B/s]

presto> show functions like '%H3%';
 Function | Return Type | Argument Types | Function Type | Deterministic | Description | Variable Arity | Built In | Temporary | Language 
----------+-------------+----------------+---------------+---------------+-------------+----------------+----------+-----------+----------
(0 rows)
```
Please let me know where I am going wrong with this. A prompt response will be much appreciated. 

@isaacbrodsky
@nrabinowitz

**Comment by isaacbrodsky** [comment]
`No service providers of type com.facebook.presto.spi.Plugin` this does not look right while loading the H3Plugin. It sounds like it cannot find the plugin class, `[com.foursquare.presto.h3.H3Plugin](https://github.com/foursquare/h3-presto/blob/main/src/main/java/com/foursquare/presto/h3/H3Plugin.java)`.

What version of Presto are you using? If it is not 0.277, could you try rebuilding the plugin with the Presto version set to your version https://github.com/foursquare/h3-presto/blob/main/pom.xml#L74?

Could you confirm the H3Plugin class is in the JAR at the appropriate location, and that the JAR contains the META-INF file https://github.com/foursquare/h3-presto/blob/main/src/main/resources/META-INF/services/com.facebook.presto.spi.Plugin?

**Comment by sujoyuta** [comment]
Thanks for the prompt response @isaacbrodsky . So we use presto 0.282 and I updated it as you mentioned and tried to deploy. Now the coordinator and worker fails to load the plugin with the following error

`2024-03-20T17:27:01.853Z        INFO    main    com.facebook.presto.server.PluginManager        -- Loading plugin /var/presto/data/plugin/H3Plugin --
2024-03-20T17:27:01.862Z        ERROR   main    com.facebook.presto.server.PrestoServer com.facebook.presto.spi.Plugin: com.foursquare.presto.h3.H3Plugin Unable to get public no-arg constructor
java.util.ServiceConfigurationError: com.facebook.presto.spi.Plugin: com.foursquare.presto.h3.H3Plugin Unable to get public no-arg constructor
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:673)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:270)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:234)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:218)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:210)
        at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:191)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:155)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:93)
Caused by: java.lang.NoClassDefFoundError: org/locationtech/jts/geom/Geometry
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getConstructor0(Class.java:3342)
        at java.base/java.lang.Class.getConstructor(Class.java:2151)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:660)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:657)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:668)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: org.locationtech.jts.geom.Geometry
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
        at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:85)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 19 more`

**Comment by isaacbrodsky** [comment]
With Presto 0.286 or 0.282 (OpenJDK 8 as suggested in the Presto docs. Linux aarch64 running in Docker on Mac OSX arm) I get this error:
```
2024-03-21T19:47:15.110Z	INFO	main	com.facebook.presto.server.PluginManager	-- Loading plugin /data/plugin/h3 --
2024-03-21T19:47:15.113Z	ERROR	main	com.facebook.presto.server.PrestoServer	com.facebook.presto.spi.Plugin: Provider com.foursquare.presto.h3.H3Plugin could not be instantiated
java.util.ServiceConfigurationError: com.facebook.presto.spi.Plugin: Provider com.foursquare.presto.h3.H3Plugin could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:273)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:234)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:217)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:209)
	at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:190)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:145)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)
Caused by: java.lang.NoClassDefFoundError: org/locationtech/jts/geom/Geometry
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.locationtech.jts.geom.Geometry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more
```

I also had to skip tests when building.

I can see in Presto's changelog that they upgraded JTS in 0.278 (https://prestodb.io/docs/current/release/release-0.278.html) so maybe that is related.

I tried testing with 0.277 but it might be stuck in startup, I had to switch the Docker platform back to linux/amd64 which can degrade performance, I'll update if it starts up eventually.

I tried testing with OpenJDK 17 but it seemed Presto was not compatible with that.

**Comment by tdcmeehan** [comment]
@isaacbrodsky seems we can configure the Maven shade plugin to relocate the JTS classes?

**Comment by tdcmeehan** [comment]
@isaacbrodsky opened https://github.com/foursquare/h3-presto/pull/20

**Comment by isaacbrodsky** [comment]
Thanks for the PR @tdcmeehan  -- it may take me a few days to review and I might only be able to get to it on the weekend

**Comment by sujoyuta** [comment]
Closing this. Thanks @tdcmeehan and @isaacbrodsky
